-- Objectifs commerciaux, par personne et pour l'equipe (NOS-1173).
--
-- Fichier en ASCII pur : `scripts/supabase-push.sh` passe la migration a
-- `jq --arg` apres un `cat`, et sous Git Bash / Windows tout caractere
-- non-ASCII y devient U+FFFD. Voir 20260827100000.
--
-- ---------------------------------------------------------------------------
-- Pourquoi cette table
-- ---------------------------------------------------------------------------
-- L'audit UX du 29 aout 2026 : "912 k EUR de pipeline, mais contre quel
-- objectif ? Un chiffre sans referentiel n'est pas un instrument de pilotage,
-- c'est une decoration." Rien en base ne portait cet objectif.
--
-- ---------------------------------------------------------------------------
-- Trois choix de modelisation
-- ---------------------------------------------------------------------------
-- 1. `sales_id` NULLABLE, et c'est le pivot du modele : une ligne sans
--    responsable est l'objectif COMMUN de l'equipe. Deux tables auraient
--    duplique la periode, le montant, la metrique et toutes les regles de
--    calcul pour une seule difference.
--
-- 2. Des BORNES DE DATE, pas un trimestre. "25 k EUR de MRR d'ici la fin de
--    l'annee" n'est pas un trimestre, et un enum trimestriel aurait force a
--    decouper un objectif annuel en quatre chiffres que personne n'a fixes.
--    Les bornes sont incluses, comme partout ailleurs dans ce depot.
--
-- 3. Une METRIQUE explicite. Le tableau de bord parle surtout en ARR, Simon a
--    formule son objectif en MRR, et les deux vivent cote a cote sur une
--    opportunite. Un objectif qui ne dit pas ce qu'il compte serait compare a
--    la mauvaise colonne -- d'un facteur douze.
create table if not exists public.targets (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    -- NULL = objectif commun a l'equipe.
    --
    -- `on delete cascade` : un objectif personnel n'a plus de sens quand la
    -- personne n'est plus la. Il ne faut surtout pas qu'il retombe a NULL, ce
    -- qui le transformerait silencieusement en objectif d'equipe.
    sales_id bigint references public.sales (id) on delete cascade,

    -- 'mrr' ou 'arr'. Texte plutot qu'enum, comme `deals.stage` : ajouter une
    -- metrique ne doit pas demander une migration de type.
    metric text not null default 'mrr',

    -- Bornes incluses.
    period_start date not null,
    period_end date not null,

    -- En euros, pas en centimes -- contrairement aux prix de contrat. Un
    -- objectif est un chiffre rond decide par un humain (25 000), jamais le
    -- resultat d'un calcul ou d'une facture : il n'y a pas d'erreur d'arrondi
    -- a craindre, et le stocker en centimes ferait lire 2500000 en base.
    amount numeric not null,

    -- Qui l'a pose. Rempli par trigger, comme partout ailleurs.
    author_id bigint references public.sales (id),

    constraint targets_period_ordered check (period_end >= period_start),
    constraint targets_amount_positive check (amount > 0)
);

-- Un seul objectif par personne, metrique et periode.
--
-- Deux index partiels et non une contrainte unique : en SQL, NULL n'est egal a
-- rien, pas meme a lui-meme, si bien qu'une contrainte portant sur `sales_id`
-- laisserait creer autant d'objectifs d'equipe qu'on veut sur la meme periode
-- -- exactement le cas ou le doublon fait le plus de degats, puisque l'ecran
-- en afficherait un au hasard.
create unique index if not exists targets_personal_unique
    on public.targets (sales_id, metric, period_start, period_end)
    where sales_id is not null;

create unique index if not exists targets_team_unique
    on public.targets (metric, period_start, period_end)
    where sales_id is null;

create index if not exists targets_period_idx
    on public.targets (period_start, period_end);

comment on table public.targets is
  'Objectifs commerciaux (NOS-1173). Une ligne sans sales_id est l''objectif '
  'commun de l''equipe. Bornes de date plutot que trimestre : "25 k EUR de '
  'MRR d''ici la fin de l''annee" n''est pas un trimestre.';

comment on column public.targets.metric is
  'mrr ou arr. Un objectif qui ne dit pas ce qu''il compte serait compare a la '
  'mauvaise colonne, d''un facteur douze.';

alter table public.targets enable row level security;

-- Lecture et ecriture ouvertes aux utilisateurs authentifies.
--
-- Reserver l'ecriture aux administrateurs serait defendable, mais l'equipe
-- compte trois personnes et Simon a demande que la saisie vive dans le
-- cockpit, pas dans un ecran d'administration. `author_id` garde la trace de
-- qui a pose le chiffre, ce qui suffit a cette echelle.
create policy "Enable read access for authenticated users"
  on public.targets for select to authenticated using (true);
create policy "Enable insert for authenticated users only"
  on public.targets for insert to authenticated with check (true);
create policy "Enable update for authenticated users only"
  on public.targets for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users only"
  on public.targets for delete to authenticated using (true);

grant all on table public.targets to authenticated;
grant all on table public.targets to service_role;
grant usage, select on sequence public.targets_id_seq to authenticated;
grant usage, select on sequence public.targets_id_seq to service_role;

-- `author_id` rempli automatiquement.
--
-- `set_sales_id_default` ecrit dans la colonne `sales_id`, qui porte ici un
-- tout autre sens -- le titulaire de l'objectif, et NULL pour l'equipe. Le
-- reutiliser remplirait donc le titulaire avec l'auteur, et il deviendrait
-- impossible de creer un objectif d'equipe.
create or replace function public.set_target_author_default()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.author_id is null then
    select s.id into new.author_id
    from public.sales s
    where s.user_id = auth.uid();
  end if;
  return new;
end;
$$;

create trigger set_targets_author
  before insert on public.targets
  for each row execute function public.set_target_author_default();

create trigger targets_set_updated_at
  before update on public.targets
  for each row execute function public.set_updated_at();
