-- Socle pipeline et données (NOS-796/797, 803/804, 805, 806, 807/808, 810/811/812)
--
-- This migration is strictly additive and reversible:
--   * no column is dropped,
--   * no row is deleted,
--   * the pre-migration stage of every deal is preserved in `legacy_stage`.
--
-- It is hand-written rather than generated by `supabase db diff` because
-- supabase/schemas/01_tables.sql had drifted from the applied migrations
-- (companies.type, deals.company_type and deals.trial_start_date were only ever
-- added by migrations). A generated diff would have emitted DROP COLUMN for
-- them. The declarative schema is realigned in the same commit.

-- ---------------------------------------------------------------------------
-- 1. New columns
-- ---------------------------------------------------------------------------

-- NOS-796 — keep the original stage so the pipeline migration below is reversible.
alter table public.deals add column if not exists legacy_stage text;

-- NOS-805 — date the deal entered the pipeline. `won_at` already exists and now
-- carries the signature date.
alter table public.deals add column if not exists entered_at date;

-- NOS-806 — commercial priority.
alter table public.deals add column if not exists priority text not null default 'normal';

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'deals_priority_check'
    ) then
        alter table public.deals
            add constraint deals_priority_check
            check (priority in ('normal', 'important', 'urgent'));
    end if;
end
$$;

-- Sorting on the text column would order alphabetically (important < normal <
-- urgent), which is not the urgency order. Expose a numeric rank to sort on.
alter table public.deals add column if not exists priority_rank smallint
    generated always as (
        case priority when 'urgent' then 2 when 'important' then 1 else 0 end
    ) stored;

-- NOS-803/804 — lead origin, and the sales who brought it in (distinct from the
-- owner held in sales_id).
alter table public.deals add column if not exists lead_source text;
alter table public.deals add column if not exists referrer_id bigint;

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'deals_referrer_id_fkey'
    ) then
        alter table public.deals
            add constraint deals_referrer_id_fkey
            foreign key (referrer_id) references public.sales(id) on delete set null;
    end if;
end
$$;

-- NOS-807/808 — `amount` is the ARR in euros; MRR is always derived from it.
alter table public.deals add column if not exists mrr numeric
    generated always as (round(amount::numeric / 12, 2)) stored;

-- NOS-811/812 — remember that an ARR was typed by hand so the establishment-type
-- prefill can never overwrite it.
alter table public.deals add column if not exists arr_is_manual boolean not null default false;

-- NOS-810 — establishment type drives the suggested ARR tier.
alter table public.companies add column if not exists establishment_type text;

-- ---------------------------------------------------------------------------
-- 2. Backfill (non-destructive)
-- ---------------------------------------------------------------------------

-- Existing deals entered the pipeline when they were created.
update public.deals
set entered_at = created_at::date
where entered_at is null;

-- Every existing amount was typed by a human, so protect it from the prefill.
update public.deals
set arr_is_manual = true
where amount is not null and amount <> 0 and arr_is_manual = false;

-- ---------------------------------------------------------------------------
-- 3. Canonical 8-stage pipeline (NOS-796)
-- ---------------------------------------------------------------------------
--
-- Canonical stages: lead, qualified, demo-booked, proposal-to-send,
-- proposal-sent, closed-won, perdu, churn.
--
-- lead / qualified / closed-won / perdu keep their existing slugs, so only the
-- five retired stages below move. `legacy_stage` records where each row came
-- from; the mapping can be undone with:
--     update public.deals set stage = legacy_stage where legacy_stage is not null;
--
--   follow-up    (Suivi)             -> qualified         still being nurtured
--   rdv-prix     (Rendez-vous prix)  -> demo-booked       a meeting is booked
--   trial        (Essai)             -> proposal-to-send  demo done, proposal next
--   trial-failed (Essai échoué)      -> perdu             lost
--   declined     (Décliné)           -> perdu             lost

update public.deals
set legacy_stage = stage,
    stage = case stage
        when 'follow-up' then 'qualified'
        when 'rdv-prix' then 'demo-booked'
        when 'trial' then 'proposal-to-send'
        when 'trial-failed' then 'perdu'
        when 'declined' then 'perdu'
    end
where stage in ('follow-up', 'rdv-prix', 'trial', 'trial-failed', 'declined')
  and legacy_stage is null;

-- ---------------------------------------------------------------------------
-- 4. Views
-- ---------------------------------------------------------------------------
-- `select d.*` is expanded and frozen when a view is created, so both summary
-- views must be dropped and recreated to expose the new columns. CREATE OR
-- REPLACE cannot change a view's column list.

drop view if exists public.deals_summary;

create view public.deals_summary
  with (security_invoker = on)
  as
select
    d.*,
    -- Filterable mirror of company_type with NULL folded to '' (NOS-797).
    -- PostgREST evaluates `not.in.(...)` as NULL for a NULL column and drops
    -- the row, which would have hidden every untyped opportunity — exactly the
    -- ones the commercial pipeline is made of.
    coalesce(d.company_type, '')                                                                                       as company_type_key,
    comp.name                                                                                                          as company_name,
    replace(lower(immutable_unaccent(coalesce(comp.name, ''))), ' ', '')                                                as company_name_search,
    coalesce(string_agg((c.first_name || ' ' || c.last_name), ' '), '')                                                as contact_names,
    replace(lower(immutable_unaccent(coalesce(string_agg((c.first_name || ' ' || c.last_name), ' '), ''))), ' ', '')    as contact_names_search
from public.deals d
    left join public.contacts c on c.id = any(d.contact_ids)
    left join public.companies comp on comp.id = d.company_id
group by d.id, comp.name;

-- Re-apply grants (DROP VIEW resets them)
revoke all on table public.deals_summary from anon;
grant all on table public.deals_summary to authenticated;
grant all on table public.deals_summary to service_role;

drop view if exists public.companies_summary;

create view public.companies_summary
  with (security_invoker = on)
  as
select
    c.*,
    count(distinct d.id) as nb_deals,
    count(distinct co.id) as nb_contacts
from public.companies c
    left join public.deals d on c.id = d.company_id
    left join public.contacts co on c.id = co.company_id
group by c.id;

revoke all on table public.companies_summary from anon;
grant all on table public.companies_summary to authenticated;
grant all on table public.companies_summary to service_role;

-- ---------------------------------------------------------------------------
-- 5. Indexes supporting the new list view filters
-- ---------------------------------------------------------------------------

create index if not exists deals_priority_rank_idx on public.deals using btree (priority_rank);
create index if not exists deals_company_type_idx on public.deals using btree (company_type);
