-- Contrats POC et cadre, generes depuis une opportunite (NOS-1156).
--
-- Fichier en ASCII pur : `scripts/supabase-push.sh` passe la migration a
-- `jq --arg` apres un `cat`, et sous Git Bash / Windows tout caractere
-- non-ASCII y devient U+FFFD. Voir 20260827100000.

-- ---------------------------------------------------------------------------
-- 1. La fonction du signataire cote Nosho
-- ---------------------------------------------------------------------------
-- Le contrat cadre ecrit "Thomas Guillaumin, President" : la fonction est
-- exigee a cote du nom, dans le bloc parties comme dans le bloc signature.
--
-- Portee par `sales` et non par le contrat, parce qu'elle appartient a la
-- personne : elle ne change pas d'un contrat a l'autre, et la repeter a chaque
-- saisie garantit qu'un jour deux contrats donneront deux fonctions
-- differentes au meme signataire.
--
-- Trois personnes peuvent signer selon Simon : Thomas Guillaumin, Simon
-- Sallandre, Marc-Henri Bonamy. Leurs fonctions restent a renseigner.
alter table public.sales
  add column if not exists job_title text;

comment on column public.sales.job_title is
  'Fonction affichee sur les contrats, ex. ''President''. Attribut de la '
  'personne : le contrat la reprend, il ne la redefinit pas (NOS-1156).';

-- ---------------------------------------------------------------------------
-- 2. Les contrats
-- ---------------------------------------------------------------------------
create table if not exists public.contracts (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    deal_id bigint not null references public.deals (id) on delete cascade,
    company_id bigint references public.companies (id),
    -- Qui a etabli le contrat. Distinct du signataire ci-dessous : le
    -- commercial qui prepare n'est pas toujours celui qui signe.
    sales_id bigint references public.sales (id),

    -- 'poc' ou 'cadre'. Volontairement du texte et non un enum : ajouter un
    -- type de contrat ne doit pas demander une migration de type.
    kind text not null,

    -- ---------------------------------------------------------------------
    -- Signataire cote client
    -- ---------------------------------------------------------------------
    -- L'email n'est pas un confort : c'est l'adresse a laquelle part la
    -- demande de signature.
    signatory_first_name text,
    signatory_last_name text,
    signatory_job_title text,
    signatory_email text,
    -- Referent operationnel, distinct du signataire dans le contrat cadre
    -- meme si les deux coincident chez HEM.
    referent_email text,

    -- Signataire cote Nosho, fige au moment de l'edition : si quelqu'un
    -- change de fonction ensuite, le contrat deja signe ne doit pas changer
    -- de sens retroactivement.
    nosho_signatory_id bigint references public.sales (id),
    nosho_signatory_job_title text,

    -- ---------------------------------------------------------------------
    -- Offre et prix
    -- ---------------------------------------------------------------------
    -- Le triplet du contrat : "Forfait confirmation" / "Appel sortant de
    -- confirmation, par rendez-vous traite" / 0,25 EUR par confirmation.
    --
    -- Pas de liste fermee de services : la grille de reference du contrat
    -- compte quatre offres (Essentiel, Avance, Hopital, Pay-per-use) mais le
    -- tarif contractuel est celui negocie, et l'unite change avec l'offre
    -- (par mois, par confirmation, par rendez-vous).
    offer_label text,
    offer_detail text,
    -- En centimes : un prix de 0,25 EUR en flottant finit par valoir
    -- 0,2500000000000001, et une facture ne se discute pas sur une
    -- approximation binaire.
    unit_price_cents integer,
    price_unit text,

    -- ---------------------------------------------------------------------
    -- Duree
    -- ---------------------------------------------------------------------
    -- Article 7 : periode ferme de 12 mois A COMPTER DE LA MISE EN
    -- PRODUCTION, puis tacite reconduction par periodes de 12 mois, preavis
    -- de 30 jours.
    --
    -- Il n'y a donc pas de date de fin, et c'est deliberement absent de cette
    -- table : en stocker une contredirait l'article et donnerait un chiffre
    -- faux a quiconque le lirait.
    commitment_months integer not null default 12,
    renewal_months integer not null default 12,
    notice_days integer not null default 30,
    -- Renseignee plus tard : elle demarre la periode ferme, et n'est connue
    -- ni a la signature ni a l'edition.
    production_start_date date,

    -- ---------------------------------------------------------------------
    -- Mandat SEPA (contrat cadre seulement)
    -- ---------------------------------------------------------------------
    -- La RUM est generee et doit rester unique : la banque du debiteur
    -- l'enregistre, et deux mandats partageant une RUM se telescopent.
    sepa_mandate_reference text unique,
    -- Mandat B2B : le debiteur doit le transmettre lui-meme a sa banque, et
    -- rien n'est prelevable avant cet enregistrement. Aucun outil ne peut le
    -- savoir -- d'ou une date saisie a la main, sur retour du client.
    sepa_registered_at date,

    -- ---------------------------------------------------------------------
    -- Cycle de vie
    -- ---------------------------------------------------------------------
    -- draft -> generated -> sent -> signed. Texte plutot qu'enum, pour la
    -- meme raison que `kind`.
    status text not null default 'draft',
    document_url text,
    signed_document_url text,
    sent_at timestamp with time zone,
    signed_at timestamp with time zone
);

create index if not exists contracts_deal_id_idx on public.contracts (deal_id);
create index if not exists contracts_status_idx on public.contracts (status);

comment on table public.contracts is
  'Contrats POC et cadre edites depuis une opportunite (NOS-1156). Pas de '
  'date de fin : l''article 7 du contrat cadre pose une periode ferme comptee '
  'depuis la mise en production, puis une tacite reconduction.';

alter table public.contracts enable row level security;

create policy "Enable read access for authenticated users"
  on public.contracts for select to authenticated using (true);
create policy "Enable insert for authenticated users only"
  on public.contracts for insert to authenticated with check (true);
create policy "Enable update for authenticated users only"
  on public.contracts for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users only"
  on public.contracts for delete to authenticated using (true);

grant all on table public.contracts to authenticated;
grant all on table public.contracts to service_role;
grant usage, select on sequence public.contracts_id_seq to authenticated;
grant usage, select on sequence public.contracts_id_seq to service_role;

-- `sales_id` rempli automatiquement, comme sur les autres tables (migration
-- 20260108160722).
create trigger set_contracts_sales_id
  before insert on public.contracts
  for each row execute function public.set_sales_id_default();

create trigger contracts_set_updated_at
  before update on public.contracts
  for each row execute function public.set_updated_at();
