-- Journal d'audit des opportunités (issue #114)
--
-- La fiche opportunité doit montrer trois choses : les notes, les tâches, et
-- les *mises à jour* — toute édition de l'opportunité. Seuls les changements
-- d'étape étaient historisés. `deal_change_log` généralise ça à tous les champs
-- métier, et `deal_stage_history` survit comme vue pour ne rien casser côté
-- front.
--
-- Écrite à la main : `supabase db diff` est inutilisable sur ce projet.
-- `config.toml` ne déclare pas de [db.migrations] schema_paths, donc le CLI ne
-- lit jamais supabase/schemas/ ; et les dix colonnes générées `*_search` vivent
-- en production sans y être déclarées, donc un diff généré émettrait un
-- DROP COLUMN pour chacune (cf. 01_tables.sql, « do not run it »).

-- ---------------------------------------------------------------------------
-- 1. La table
-- ---------------------------------------------------------------------------

create table if not exists public.deal_change_log (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    operation text not null default 'update',
    field text not null,
    -- jsonb : la même colonne porte un scalaire (`amount`) et un tableau
    -- (`contact_ids bigint[]`) sans perdre les identifiants.
    old_value jsonb,
    new_value jsonb,
    changed_at timestamp with time zone not null default now(),
    changed_by bigint,
    source text not null default 'user',
    constraint deal_change_log_operation_check check (operation in ('insert', 'update'))
);

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'deal_change_log_deal_id_fkey'
    ) then
        alter table public.deal_change_log
            add constraint deal_change_log_deal_id_fkey
            foreign key (deal_id) references public.deals(id) on delete cascade;
    end if;

    if not exists (
        select 1 from pg_constraint where conname = 'deal_change_log_changed_by_fkey'
    ) then
        alter table public.deal_change_log
            add constraint deal_change_log_changed_by_fkey
            foreign key (changed_by) references public.sales(id) on delete set null;
    end if;
end $$;

-- L'unique chemin d'accès : « pour cette opportunité, du plus récent au plus
-- ancien ». Sert aussi la vue de compatibilité ci-dessous.
create index if not exists deal_change_log_deal_idx
    on public.deal_change_log using btree (deal_id, changed_at desc);

-- ---------------------------------------------------------------------------
-- 2. RLS et droits, AVANT toute écriture
-- ---------------------------------------------------------------------------

alter table public.deal_change_log enable row level security;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'deal_change_log'
          and policyname = 'deal_change_log_select'
    ) then
        -- Lecture seule. Aucune policy INSERT : c'est un journal, il ne doit
        -- pas être forgeable. Le trigger passe parce qu'il est SECURITY DEFINER.
        create policy deal_change_log_select on public.deal_change_log
            for select to authenticated using (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'deal_change_log'
          and policyname = 'deny_anon_all'
    ) then
        create policy "deny_anon_all" on public.deal_change_log
            as restrictive for all to anon using (false) with check (false);
    end if;
end $$;

revoke all on table public.deal_change_log from anon;
grant select on table public.deal_change_log to authenticated;
grant all    on table public.deal_change_log to service_role;

-- ---------------------------------------------------------------------------
-- 3. La fonction trigger
-- ---------------------------------------------------------------------------
--
-- SECURITY DEFINER n'est pas cosmétique : `deal_change_log` a RLS activé avec
-- SELECT pour seule policy, donc un trigger tournant avec les droits de
-- l'appelant ne peut pas insérer. Livré sans, le 2026-08-23, ça a bloqué tout
-- changement d'étape pendant ~19 h — et comme PostgREST renvoie 403 sur une
-- violation RLS, ra-supabase déconnectait l'utilisateur au lieu d'afficher une
-- erreur (cf. 20260824090000_fix_stage_history_rls.sql).
--
-- Le bloc EXCEPTION est l'autre moitié de la leçon : le journal vaut moins que
-- l'opportunité. Un échec ici devient un WARNING, jamais un rollback du parent.

CREATE OR REPLACE FUNCTION "public"."log_deal_change"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  -- Liste blanche. Tout ce qui n'y est pas n'est jamais journalisé — c'est ce
  -- qui garde à la fois le volume et la timeline lisibles :
  --   * updated_at            réécrit à chaque save, changerait sur 100 % des
  --                           updates et doublerait chaque entrée ;
  --   * index                 ordonnancement kanban, réécrit sur toute une
  --                           colonne à chaque drag & drop ;
  --   * mrr, priority_rank    colonnes générées, doubleraient amount/priority ;
  --     name_search, …
  --   * won_at                dérivé de stage ;
  --   * arr_is_manual         effet de bord de la saisie d'un montant ;
  --   * legacy_stage/category comptabilité de migration, jamais du métier.
  v_tracked constant text[] := array[
    'stage', 'amount', 'priority', 'sales_id', 'expected_closing_date',
    'contact_ids', 'products', 'contact_roles',
    'name', 'company_id', 'company_type', 'opportunity_type', 'category',
    'lead_source', 'referrer_id', 'probability', 'description',
    'next_action', 'next_action_date', 'next_action_owner_id',
    'trial_start_date', 'entered_at', 'archived_at'
  ];
  v_old      jsonb;
  v_new      jsonb;
  v_field    text;
  v_before   jsonb;
  v_after    jsonb;
  v_sales_id bigint;
  v_source   text;
BEGIN
  -- auth.uid() est NULL sous service_role et sous la Management API : la ligne
  -- reste non attribuée plutôt que l'écriture n'échoue.
  SELECT id INTO v_sales_id FROM sales WHERE user_id = auth.uid();
  v_source := coalesce(nullif(current_setting('app.change_source', true), ''), 'user');

  -- Une création = une entrée, pas une par colonne : une opportunité neuve avec
  -- quinze lignes « -> valeur » noierait la timeline qu'elle ouvre.
  IF TG_OP = 'INSERT' THEN
    INSERT INTO deal_change_log (deal_id, operation, field, old_value, new_value, changed_by, source)
    VALUES (NEW.id, 'insert', 'stage', NULL, to_jsonb(NEW.stage), v_sales_id, v_source);
    RETURN NULL;
  END IF;

  v_old := to_jsonb(OLD);
  v_new := to_jsonb(NEW);

  FOREACH v_field IN ARRAY v_tracked LOOP
    v_before := v_old -> v_field;
    v_after  := v_new -> v_field;

    -- Les tableaux se comparent comme des ensembles : `contact_ids` et
    -- `products` reviennent du formulaire dans l'ordre produit par les inputs,
    -- et un simple réordonnancement n'est pas un changement métier.
    IF jsonb_typeof(v_before) = 'array' THEN
      v_before := coalesce(
        (SELECT jsonb_agg(e ORDER BY e::text) FROM jsonb_array_elements(v_before) e),
        '[]'::jsonb);
    END IF;
    IF jsonb_typeof(v_after) = 'array' THEN
      v_after := coalesce(
        (SELECT jsonb_agg(e ORDER BY e::text) FROM jsonb_array_elements(v_after) e),
        '[]'::jsonb);
    END IF;

    CONTINUE WHEN v_before IS NOT DISTINCT FROM v_after;

    -- to_jsonb() rend une colonne NULL sous la forme du JSON `null` : on
    -- stocke le NULL SQL, pour que `old_value is null` veuille dire la même
    -- chose sur une ligne du trigger et sur une ligne reprise.
    INSERT INTO deal_change_log (deal_id, operation, field, old_value, new_value, changed_by, source)
    VALUES (
      NEW.id,
      'update',
      v_field,
      nullif(v_before, 'null'::jsonb),
      nullif(v_after,  'null'::jsonb),
      v_sales_id,
      v_source
    );
  END LOOP;

  RETURN NULL;
EXCEPTION
  WHEN OTHERS THEN
    RAISE WARNING 'log_deal_change(deal %): %', NEW.id, SQLERRM;
    RETURN NULL;
END;
$$;

grant all on function public.log_deal_change() to authenticated;
grant all on function public.log_deal_change() to service_role;

-- ---------------------------------------------------------------------------
-- 4. Reprise de l'historique existant, AVANT toute suppression
-- ---------------------------------------------------------------------------

insert into public.deal_change_log
    (deal_id, operation, field, old_value, new_value, changed_at, changed_by, source)
select h.deal_id,
       case when h.from_stage is null then 'insert' else 'update' end,
       'stage',
       -- to_jsonb(NULL::text) rend le JSON `null` ; on garde le NULL SQL pour
       -- rester identique à ce qu'écrit le trigger.
       case when h.from_stage is null then null else to_jsonb(h.from_stage) end,
       to_jsonb(h.to_stage),
       h.changed_at,
       h.changed_by,
       h.source
from public.deal_stage_history h;

-- ---------------------------------------------------------------------------
-- 5. Vérification bloquante de la reprise, AVANT le drop
-- ---------------------------------------------------------------------------

do $$
declare
    v_src bigint;
    v_dst bigint;
begin
    select count(*) into v_src from public.deal_stage_history;
    select count(*) into v_dst from public.deal_change_log where field = 'stage';

    if v_src <> v_dst then
        raise exception 'Reprise de l''historique : % lignes source, % reprises', v_src, v_dst;
    end if;

    raise notice 'Historique repris : % lignes', v_dst;
end $$;

-- ---------------------------------------------------------------------------
-- 6. Bascule : anciens triggers, ancienne fonction, ancienne table, puis la vue
-- ---------------------------------------------------------------------------

drop trigger if exists deal_stage_history_on_insert on public.deals;
drop trigger if exists deal_stage_history_on_update on public.deals;
drop function if exists public.log_deal_stage_change();

-- Sans `cascade`, volontairement : si un objet non identifié dépend de cette
-- table, la migration doit s'arrêter ici plutôt que l'emporter en silence.
drop table public.deal_stage_history;

create or replace view public.deal_stage_history with (security_invoker = on) as
select
    l.id,
    l.deal_id,
    -- `#>> '{}'` déballe un scalaire jsonb en texte non quoté et renvoie NULL
    -- aussi bien pour un NULL SQL que pour un `'null'::jsonb`.
    l.old_value #>> '{}' as from_stage,
    l.new_value #>> '{}' as to_stage,
    l.changed_at,
    l.changed_by,
    l.source
from public.deal_change_log l
where l.field = 'stage';

revoke all on table public.deal_stage_history from anon;
grant select on table public.deal_stage_history to authenticated;
grant all    on table public.deal_stage_history to service_role;

-- ---------------------------------------------------------------------------
-- 7. Les nouveaux triggers
-- ---------------------------------------------------------------------------

create or replace trigger deal_change_log_on_insert
    after insert on public.deals
    for each row execute function public.log_deal_change();

-- Pas de clause WHEN : la liste blanche vit dans la fonction. La répéter ici
-- serait une seconde copie qui dériverait.
create or replace trigger deal_change_log_on_update
    after update on public.deals
    for each row execute function public.log_deal_change();

-- ---------------------------------------------------------------------------
-- 8. Sonde : exerce le vrai chemin sous le rôle de l'application, puis annule
-- ---------------------------------------------------------------------------

do $$
declare
    v_deal_id bigint;
    v_prio    text;
    v_max_id  bigint;
    v_rows    bigint;
    v_fields  text[];
begin
    select id, priority into v_deal_id, v_prio
      from public.deals where archived_at is null order by id limit 1;

    if v_deal_id is null then
        raise notice 'Aucune opportunité à tester';
        return;
    end if;

    select coalesce(max(id), 0) into v_max_id from public.deal_change_log;

    -- Le contrôle de privilèges est ce qui compte : il doit tourner sous le
    -- rôle que l'application utilise, pas sous le propriétaire de la migration.
    set local role authenticated;
    -- Deux champs sans contrainte de valeur : `deals_priority_check` accepte
    -- les trois valeurs ci-dessous, et une date n'a pas de borne. Toucher
    -- `probability` serait un piège — `deals_probability_check` la plafonne à
    -- 100, et une opportunité à 100 ferait échouer toute la migration.
    update public.deals
       set priority = case when v_prio = 'urgent' then 'normal' else 'urgent' end,
           expected_closing_date = coalesce(expected_closing_date, current_date) + 1
     where id = v_deal_id;
    reset role;

    select count(*), array_agg(field order by field)
      into v_rows, v_fields
      from public.deal_change_log where id > v_max_id;

    -- Exactement deux lignes : une par champ suivi. Si `updated_at`, `index`,
    -- `mrr` ou `priority_rank` avaient fui la liste blanche, le compte serait
    -- plus élevé et la sonde échouerait.
    if v_rows <> 2 or v_fields is distinct from array['expected_closing_date', 'priority'] then
        raise exception 'Journal d''audit : attendu 2 lignes (expected_closing_date, priority), obtenu % (%)',
            v_rows, v_fields;
    end if;

    raise notice 'Journal vérifié sous le rôle authenticated : % lignes, %', v_rows, v_fields;

    raise exception 'ROLLBACK_SONDE';
exception
    when others then
        if sqlerrm = 'ROLLBACK_SONDE' then
            raise notice 'Sonde annulée, données de production intactes';
        else
            raise;
        end if;
end $$;

-- Le passage table -> vue change la définition exposée par PostgREST.
notify pgrst, 'reload schema';
