-- Deal page: company groups, stage history, deal-scoped tasks (NOS-957/958, NOS-819)
--
-- Strictly additive. No column dropped, no row deleted, and the only constraint
-- loosened is `tasks.contact_id`, which becomes nullable so a task can belong to
-- an opportunity instead of a contact.
--
-- Hand-written: `supabase db diff` is unusable here, the ten stored generated
-- `*_search` columns live in production but are not declared in
-- supabase/schemas/, so a generated diff emits DROP COLUMN for each.

-- ---------------------------------------------------------------------------
-- 1. Company groups (NOS-957 §4)
-- ---------------------------------------------------------------------------
--
-- A self-reference rather than a `groups` table: a parent company is a company.
-- Giving groups their own table would mean two entities to search, two to
-- merge and two to enrich, for a relation the existing one already expresses.
-- "Le groupe doit être enregistré, réutilisable sur plusieurs sociétés,
-- cliquable" — all three come free from a company.
--
-- `on delete set null`: deleting a parent must orphan its subsidiaries, never
-- cascade into deleting them.

alter table public.companies add column if not exists parent_company_id bigint;

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'companies_parent_company_id_fkey'
    ) then
        alter table public.companies
            add constraint companies_parent_company_id_fkey
            foreign key (parent_company_id) references public.companies(id) on delete set null;
    end if;
end
$$;

create index if not exists companies_parent_company_id_idx
    on public.companies using btree (parent_company_id);

-- A company cannot be its own ancestor. Without this, a cycle makes every
-- recursive read of the hierarchy hang — and the UI walks it to render the
-- breadcrumb.
CREATE OR REPLACE FUNCTION "public"."check_company_parent_cycle"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_parent bigint := NEW.parent_company_id;
  v_depth  integer := 0;
BEGIN
  WHILE v_parent IS NOT NULL LOOP
    IF v_parent = NEW.id THEN
      RAISE EXCEPTION 'Cycle detecte dans la hierarchie de societes (societe %)', NEW.id;
    END IF;
    v_depth := v_depth + 1;
    IF v_depth > 20 THEN
      RAISE EXCEPTION 'Hierarchie de societes trop profonde (societe %)', NEW.id;
    END IF;
    SELECT parent_company_id INTO v_parent FROM companies WHERE id = v_parent;
  END LOOP;
  RETURN NEW;
END;
$$;

create or replace trigger company_parent_cycle_guard
    before insert or update on public.companies
    for each row
    when (new.parent_company_id is not null)
    execute function public.check_company_parent_cycle();

-- ---------------------------------------------------------------------------
-- 2. Stage history (NOS-958 §7, NOS-819)
-- ---------------------------------------------------------------------------
--
-- "Réutiliser l'historique existant s'il est disponible. Ne pas créer un second
-- historique parallèle." There was none: `legacy_stage` holds a single
-- migration snapshot, and `activity_log` never covered stage changes. This is
-- the first and only one.
--
-- Written by a trigger rather than by the application, because the board moves
-- deals by drag & drop straight through the data provider — an application-side
-- write would miss every one of them.

create table if not exists public.deal_stage_history (
    id bigint generated by default as identity primary key,
    deal_id bigint not null,
    -- NULL on creation: the deal had no previous stage.
    from_stage text,
    to_stage text not null,
    changed_at timestamp with time zone not null default now(),
    -- NULL when the change came from a migration or a service-role script,
    -- where auth.uid() resolves to nothing.
    changed_by bigint,
    -- 'user' | 'migration' | 'rollback'. Lets the audit tell a human decision
    -- from a bulk one.
    source text not null default 'user'
);

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'deal_stage_history_deal_id_fkey'
    ) then
        alter table public.deal_stage_history
            add constraint deal_stage_history_deal_id_fkey
            foreign key (deal_id) references public.deals(id) on delete cascade;
    end if;
    if not exists (
        select 1 from pg_constraint where conname = 'deal_stage_history_changed_by_fkey'
    ) then
        alter table public.deal_stage_history
            add constraint deal_stage_history_changed_by_fkey
            foreign key (changed_by) references public.sales(id) on delete set null;
    end if;
end
$$;

-- The panel reads "most recent first, for this deal".
create index if not exists deal_stage_history_deal_idx
    on public.deal_stage_history using btree (deal_id, changed_at desc);

CREATE OR REPLACE FUNCTION "public"."log_deal_stage_change"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_sales_id bigint;
BEGIN
  -- auth.uid() is NULL under service_role and under the Management API, so the
  -- row is simply left unattributed rather than the write failing.
  SELECT id INTO v_sales_id FROM sales WHERE user_id = auth.uid();

  INSERT INTO deal_stage_history (deal_id, from_stage, to_stage, changed_by, source)
  VALUES (
    NEW.id,
    CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.stage END,
    NEW.stage,
    v_sales_id,
    coalesce(nullif(current_setting('app.change_source', true), ''), 'user')
  );
  RETURN NULL;
END;
$$;

create or replace trigger deal_stage_history_on_insert
    after insert on public.deals
    for each row execute function public.log_deal_stage_change();

create or replace trigger deal_stage_history_on_update
    after update on public.deals
    for each row
    when (old.stage is distinct from new.stage)
    execute function public.log_deal_stage_change();

-- Seed the history from what is already known, so the panel is not empty on
-- day one. `entered_at` dates the arrival in the pipeline; `legacy_stage`
-- records where the migration found the deal.
insert into public.deal_stage_history (deal_id, from_stage, to_stage, changed_at, source)
select d.id,
       d.legacy_stage,
       d.stage,
       coalesce(d.entered_at::timestamptz, d.created_at),
       'migration'
from public.deals d
where not exists (
    select 1 from public.deal_stage_history h where h.deal_id = d.id
);

-- ---------------------------------------------------------------------------
-- 3. Tasks on opportunities (NOS-958 §6)
-- ---------------------------------------------------------------------------
--
-- `contact_id` was NOT NULL, so nothing could be attached to a deal — which is
-- why the timeline had no "Actions" to show. A completed next action has to
-- land somewhere durable, and tasks are that place.

alter table public.tasks alter column contact_id drop not null;
alter table public.tasks add column if not exists deal_id bigint;

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'tasks_deal_id_fkey'
    ) then
        alter table public.tasks
            add constraint tasks_deal_id_fkey
            foreign key (deal_id) references public.deals(id) on delete cascade;
    end if;
    -- A task with neither owner would be unreachable from any screen.
    if not exists (
        select 1 from pg_constraint where conname = 'tasks_owner_check'
    ) then
        alter table public.tasks
            add constraint tasks_owner_check
            check (contact_id is not null or deal_id is not null);
    end if;
end
$$;

create index if not exists tasks_deal_id_idx on public.tasks using btree (deal_id);

-- ---------------------------------------------------------------------------
-- 4. Views
-- ---------------------------------------------------------------------------
--
-- DROP + CREATE, never CREATE OR REPLACE: `select c.*` is expanded and frozen
-- at creation time, so the view must be rebuilt to expose `parent_company_id`.
-- DROP also resets privileges, hence the re-grants.

drop view if exists public.companies_summary;

create view public.companies_summary
  with (security_invoker = on)
  as
select
    c.*,
    count(distinct d.id) as nb_deals,
    count(distinct co.id) as nb_contacts,
    -- Scalar subqueries, not joins: a join here would multiply the rows feeding
    -- the two count(distinct) above.
    (select p.name from public.companies p where p.id = c.parent_company_id)   as parent_company_name,
    (select count(*) from public.companies s where s.parent_company_id = c.id) as nb_subsidiaries
from public.companies c
    left join public.deals d on c.id = d.company_id
    left join public.contacts co on c.id = co.company_id
group by c.id;

revoke all on table public.companies_summary from anon;
grant all on table public.companies_summary to authenticated;
grant all on table public.companies_summary to service_role;

-- ---------------------------------------------------------------------------
-- 5. RLS and grants
-- ---------------------------------------------------------------------------

alter table public.deal_stage_history enable row level security;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'deal_stage_history'
          and policyname = 'deal_stage_history_select'
    ) then
        -- Read-only for the application: the history is written by the trigger,
        -- and nothing in the UI should be able to rewrite what happened.
        create policy deal_stage_history_select on public.deal_stage_history
            for select to authenticated using (true);
    end if;
end
$$;

revoke all on table public.deal_stage_history from anon;
grant select on table public.deal_stage_history to authenticated;
grant all on table public.deal_stage_history to service_role;

grant all on function public.check_company_parent_cycle() to authenticated, service_role;
grant all on function public.log_deal_stage_change() to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 6. Verification — blocking
-- ---------------------------------------------------------------------------

do $$
declare
    v_deals   bigint;
    v_history bigint;
    v_cycles  bigint;
begin
    select count(*) into v_deals from public.deals;
    select count(distinct deal_id) into v_history from public.deal_stage_history;

    -- Every deal must have at least one history entry after the seed.
    if v_history <> v_deals then
        raise exception 'Historique des étapes : % opportunités sur % sans entrée',
            v_deals - v_history, v_deals;
    end if;

    with recursive chain(id, parent_id, depth, path) as (
        select id, parent_company_id, 1, array[id]
          from public.companies where parent_company_id is not null
        union all
        select c.id, p.parent_company_id, chain.depth + 1, chain.path || c.id
          from chain
          join public.companies c on c.id = chain.parent_id
          left join public.companies p on p.id = c.parent_company_id
         where chain.depth < 20 and not c.id = any(chain.path)
    )
    select count(*) into v_cycles from chain where parent_id = any(path);

    if v_cycles > 0 then
        raise exception 'Hiérarchie de sociétés : % cycle(s) détecté(s)', v_cycles;
    end if;

    raise notice 'Fiche opportunité : % entrées d''historique pour % opportunités',
        (select count(*) from public.deal_stage_history), v_deals;
end
$$;
