-- Le chiffre d'affaires reellement encaisse, mois par mois (NOS-1179).
--
-- Fichier en ASCII pur : `scripts/supabase-push.sh` refuse desormais toute
-- migration contenant un caractere non-ASCII -- il les detruisait en silence
-- (cat + jq --arg sous Git Bash). Voir 20260827100000.
--
-- ---------------------------------------------------------------------------
-- Pourquoi cette table
-- ---------------------------------------------------------------------------
-- Tout le reste du CRM parle d'ARR *saisi* : un montant qu'un commercial a
-- tape dans une opportunite, au mieux confirme par une proposition. Cette
-- table porte l'autre chiffre, celui qui a vraiment atterri sur le compte :
-- la somme des virements Mollie recus chez Qonto, qui sont les paiements
-- clients.
--
-- Les deux ne se remplacent pas. L'ARR dit ce qu'on espere, l'encaisse dit ce
-- qu'on a. Les confondre dans une meme colonne rendrait impossible de voir
-- l'ecart entre les deux -- qui est precisement l'information la plus utile.
--
-- ---------------------------------------------------------------------------
-- Trois choix
-- ---------------------------------------------------------------------------
-- 1. `month` est une DATE, fixee au premier du mois, et non un couple
--    (annee, mois). Un mois est une periode : le stocker comme une date
--    permet de trier, comparer et filtrer avec les operateurs habituels, sans
--    reconstruire une cle a chaque requete.
--
-- 2. `transaction_count` est stocke a cote du montant. Il ne sert pas a
--    l'affichage : il sert a reperer une collecte partielle. Un mois qui
--    passe de huit virements a un seul, pour un montant proche, signale une
--    pagination interrompue -- pas une baisse d'activite.
--
-- 3. Une contrainte UNIQUE sur (month, source), et un `on conflict` a
--    l'insertion. La collecte est rejouable : relancer le mois de juillet
--    doit corriger le chiffre, pas en ajouter un second.
create table if not exists public.revenue_actuals (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    -- Premier jour du mois couvert.
    month date not null,

    -- 'mollie' aujourd'hui. Texte plutot qu'enum : le jour ou un client paie
    -- par virement direct, une seconde source s'ajoute sans migration de type.
    source text not null default 'mollie',

    -- En euros. Comme les objectifs, et pour la meme raison : ce sont des
    -- montants lus et compares par des humains, pas des prix a la piece.
    amount numeric not null,

    -- Nombre de virements composant le total. Voir le choix 2 ci-dessus.
    transaction_count integer,

    -- Quand la collecte a eu lieu. Distinct de `updated_at` : celui-ci bouge a
    -- chaque ecriture, celui-la dit quand la banque a ete interrogee.
    fetched_at timestamp with time zone not null default now(),

    constraint revenue_actuals_month_is_first_of_month
      check (extract(day from month) = 1),
    constraint revenue_actuals_amount_not_negative check (amount >= 0),
    constraint revenue_actuals_month_source_unique unique (month, source)
);

create index if not exists revenue_actuals_month_idx
    on public.revenue_actuals (month desc);

comment on table public.revenue_actuals is
  'Encaisse reelle par mois, depuis les virements Mollie recus chez Qonto '
  '(NOS-1179). A ne pas confondre avec l''ARR des opportunites : l''un dit ce '
  'qu''on a encaisse, l''autre ce qu''on espere.';

comment on column public.revenue_actuals.transaction_count is
  'Nombre de virements du mois. Sert a reperer une collecte partielle : huit '
  'virements devenus un, pour un montant proche, signale une pagination '
  'interrompue et non une baisse d''activite.';

alter table public.revenue_actuals enable row level security;

-- Lecture pour tous les utilisateurs authentifies ; ecriture aussi, parce que
-- la collecte se fait aujourd'hui a la main faute de cle API Qonto cote
-- serveur. A restreindre au `service_role` le jour ou une fonction planifiee
-- prend le relais.
create policy "Enable read access for authenticated users"
  on public.revenue_actuals for select to authenticated using (true);
create policy "Enable insert for authenticated users only"
  on public.revenue_actuals for insert to authenticated with check (true);
create policy "Enable update for authenticated users only"
  on public.revenue_actuals for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users only"
  on public.revenue_actuals for delete to authenticated using (true);

grant all on table public.revenue_actuals to authenticated;
grant all on table public.revenue_actuals to service_role;
grant usage, select on sequence public.revenue_actuals_id_seq to authenticated;
grant usage, select on sequence public.revenue_actuals_id_seq to service_role;

create trigger revenue_actuals_set_updated_at
  before update on public.revenue_actuals
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Amorce : les deux derniers mois complets, releves le 29 aout 2026
-- ---------------------------------------------------------------------------
-- Chiffres lus sur le compte Qonto principal, en sommant les credits dont le
-- libelle est "Stichting Mollie Payments" -- l'entite qui reverse les
-- paiements collectes par Mollie.
--
-- Aout n'y figure pas, et c'est la regle : un mois en cours n'a pas de total.
insert into public.revenue_actuals (month, source, amount, transaction_count)
values
    ('2026-06-01', 'mollie', 3123.21, 5),
    ('2026-07-01', 'mollie', 3166.31, 8)
on conflict (month, source) do update
    set amount = excluded.amount,
        transaction_count = excluded.transaction_count,
        fetched_at = now();
